name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./vihiclemanagement/pom.xml
          mvn clean package -f ./usermgmt/pom.xml
          mvn clean package -f ./point/pom.xml

      - name: Docker Build and push for Vihiclemanagement
        uses: docker/build-push-action@v4
        with:
          context: ./vihiclemanagement
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/vihiclemanagement:latest
            ghcr.io/${{ github.repository }}/vihiclemanagement:${{ github.ref_name }}
            
      - name: Docker Build and push for Usermgmt
        uses: docker/build-push-action@v4
        with:
          context: ./usermgmt
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/usermgmt:latest
            ghcr.io/${{ github.repository }}/usermgmt:${{ github.ref_name }}
            
      - name: Docker Build and push for Point
        uses: docker/build-push-action@v4
        with:
          context: ./point
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/point:latest
            ghcr.io/${{ github.repository }}/point:${{ github.ref_name }}
            
