server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: vihiclemanagement
          uri: http://localhost:8082
          predicates:
            - Path=/vehicles/**, 
        - id: usermgmt
          uri: http://localhost:8083
          predicates:
            - Path=/users/**, 
        - id: point
          uri: http://localhost:8084
          predicates:
            - Path=/pointAccumulations/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: vihiclemanagement
          uri: http://vihiclemanagement:8080
          predicates:
            - Path=/vehicles/**, 
        - id: usermgmt
          uri: http://usermgmt:8080
          predicates:
            - Path=/users/**, 
        - id: point
          uri: http://point:8080
          predicates:
            - Path=/pointAccumulations/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
